In [158]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [159]:
data = pd.read_csv("/home/akshay/Desktop/IIT_courses/Machine_Learning/ML_Project/Datasets/data.csv", sep='\t', low_memory=False )

In [160]:
data.info()
print(list(data.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39775 entries, 0 to 39774
Columns: 172 entries, Q1A to major
dtypes: int64(170), object(2)
memory usage: 52.2+ MB
['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A', 'Q4I', 'Q4E', 'Q5A', 'Q5I', 'Q5E', 'Q6A', 'Q6I', 'Q6E', 'Q7A', 'Q7I', 'Q7E', 'Q8A', 'Q8I', 'Q8E', 'Q9A', 'Q9I', 'Q9E', 'Q10A', 'Q10I', 'Q10E', 'Q11A', 'Q11I', 'Q11E', 'Q12A', 'Q12I', 'Q12E', 'Q13A', 'Q13I', 'Q13E', 'Q14A', 'Q14I', 'Q14E', 'Q15A', 'Q15I', 'Q15E', 'Q16A', 'Q16I', 'Q16E', 'Q17A', 'Q17I', 'Q17E', 'Q18A', 'Q18I', 'Q18E', 'Q19A', 'Q19I', 'Q19E', 'Q20A', 'Q20I', 'Q20E', 'Q21A', 'Q21I', 'Q21E', 'Q22A', 'Q22I', 'Q22E', 'Q23A', 'Q23I', 'Q23E', 'Q24A', 'Q24I', 'Q24E', 'Q25A', 'Q25I', 'Q25E', 'Q26A', 'Q26I', 'Q26E', 'Q27A', 'Q27I', 'Q27E', 'Q28A', 'Q28I', 'Q28E', 'Q29A', 'Q29I', 'Q29E', 'Q30A', 'Q30I', 'Q30E', 'Q31A', 'Q31I', 'Q31E', 'Q32A', 'Q32I', 'Q32E', 'Q33A', 'Q33I', 'Q33E', 'Q34A', 'Q34I', 'Q34E', 'Q35A', 'Q35I', 'Q35E', 'Q36A', 'Q36I', 'Q36E'

In [161]:
print(data)

       Q1A  Q1I    Q1E  Q2A  Q2I   Q2E  Q3A  Q3I    Q3E  Q4A  ...  screensize  \
0        4   28   3890    4   25  2122    2   16   1944    4  ...           1   
1        4    2   8118    1   36  2890    2   35   4777    3  ...           2   
2        3    7   5784    1   33  4373    4   41   3242    1  ...           2   
3        2   23   5081    3   11  6837    2   37   5521    1  ...           2   
4        2   36   3215    2   13  7731    3    5   4156    4  ...           2   
5        1   18   6116    1   28  3193    2    2  12542    1  ...           2   
6        1   20   4325    1   34  4009    2   38   3604    3  ...           2   
7        1   34   4796    1    9  2618    1   39   5823    1  ...           2   
8        4    4   3470    4   14  2139    3    1  11043    4  ...           1   
9        3   38   5187    2   28  2600    4    9   2015    1  ...           2   
10       3   38   3352    1   16  4322    2   28   3083    1  ...           1   
11       3   37   4024    3 

In [162]:
type(data)

pandas.core.frame.DataFrame

In [163]:
data["Q1A"].dtype

dtype('int64')

In [164]:
#data["Q1A"] = data["Q1A"].replace([4, 3, 2, 1],[3, 2, 1, 0])


In [165]:
#changing the response values from range 1-4 to 0-3 for the Dass 42 scales
for i in range(0,124):
    data.iloc[:, i] = data.iloc[:, i].replace([4, 3, 2, 1],[3, 2, 1, 0])
    i = i+3


    

In [166]:
print(data)

       Q1A  Q1I    Q1E  Q2A  Q2I   Q2E  Q3A  Q3I    Q3E  Q4A  ...  screensize  \
0        3   28   3890    3   25  2122    1   16   1944    3  ...           1   
1        3    1   8118    0   36  2890    1   35   4777    2  ...           2   
2        2    7   5784    0   33  4373    3   41   3242    0  ...           2   
3        1   23   5081    2   11  6837    1   37   5521    0  ...           2   
4        1   36   3215    1   13  7731    2    5   4156    3  ...           2   
5        0   18   6116    0   28  3193    1    1  12542    0  ...           2   
6        0   20   4325    0   34  4009    1   38   3604    2  ...           2   
7        0   34   4796    0    9  2618    0   39   5823    0  ...           2   
8        3    3   3470    3   14  2139    2    0  11043    3  ...           1   
9        2   38   5187    1   28  2600    3    9   2015    0  ...           2   
10       2   38   3352    0   16  4322    1   28   3083    0  ...           1   
11       2   37   4024    2 

In [167]:
data['country'].unique()

array(['IN', 'US', 'PL', 'MY', 'MX', 'GB', 'DE', 'EE', 'CA', 'EC', 'AU',
       'FI', 'ID', 'AE', 'NONE', 'ES', 'NI', 'DO', 'TR', 'NO', 'GR', 'LK',
       'BR', 'AR', 'KH', 'IT', 'MK', 'PT', 'BA', 'RU', 'HU', 'KR', 'IE',
       'RS', 'CZ', 'PH', 'RO', 'FR', 'SG', 'AT', 'UA', 'KW', 'CO', 'GE',
       'SE', 'HK', 'NZ', 'ZA', 'NL', 'DK', 'JM', 'LB', 'CL', 'AW', 'IL',
       'GT', 'PE', 'PK', 'NP', 'HR', 'CR', 'VE', 'BG', 'GH', 'MA', 'PR',
       'SI', 'LV', 'AL', 'VN', 'GU', 'BD', 'TH', 'NG', 'FO', 'UY', 'EG',
       'BE', 'SA', 'SV', 'CH', 'PY', 'SK', 'SY', 'TN', 'TT', 'SR', 'KE',
       'BY', 'PA', 'CY', 'BW', 'MZ', 'BB', 'GG', 'CW', 'IS', 'IR', 'BN',
       'MV', 'OM', 'DZ', 'JP', 'MU', nan, 'IQ', 'BO', 'MD', 'CN', 'LT',
       'BZ', 'BH', 'ME', 'QA', 'TW', 'PS', 'JO', 'SD', 'KY', 'AZ', 'AO',
       'BS', 'GY', 'MO', 'TZ', 'IM', 'AF', 'AM', 'UZ', 'LU', 'ET', 'JE',
       'VU', 'TJ', 'KZ', 'XK', 'HN', 'ZW', 'LA', 'MT', 'SN', 'MN', 'TG',
       'SC', 'RE', 'VC'], dtype=object)

In [168]:
data = data.drop(['country','major'],axis=1)

print(list(data.columns))

['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A', 'Q4I', 'Q4E', 'Q5A', 'Q5I', 'Q5E', 'Q6A', 'Q6I', 'Q6E', 'Q7A', 'Q7I', 'Q7E', 'Q8A', 'Q8I', 'Q8E', 'Q9A', 'Q9I', 'Q9E', 'Q10A', 'Q10I', 'Q10E', 'Q11A', 'Q11I', 'Q11E', 'Q12A', 'Q12I', 'Q12E', 'Q13A', 'Q13I', 'Q13E', 'Q14A', 'Q14I', 'Q14E', 'Q15A', 'Q15I', 'Q15E', 'Q16A', 'Q16I', 'Q16E', 'Q17A', 'Q17I', 'Q17E', 'Q18A', 'Q18I', 'Q18E', 'Q19A', 'Q19I', 'Q19E', 'Q20A', 'Q20I', 'Q20E', 'Q21A', 'Q21I', 'Q21E', 'Q22A', 'Q22I', 'Q22E', 'Q23A', 'Q23I', 'Q23E', 'Q24A', 'Q24I', 'Q24E', 'Q25A', 'Q25I', 'Q25E', 'Q26A', 'Q26I', 'Q26E', 'Q27A', 'Q27I', 'Q27E', 'Q28A', 'Q28I', 'Q28E', 'Q29A', 'Q29I', 'Q29E', 'Q30A', 'Q30I', 'Q30E', 'Q31A', 'Q31I', 'Q31E', 'Q32A', 'Q32I', 'Q32E', 'Q33A', 'Q33I', 'Q33E', 'Q34A', 'Q34I', 'Q34E', 'Q35A', 'Q35I', 'Q35E', 'Q36A', 'Q36I', 'Q36E', 'Q37A', 'Q37I', 'Q37E', 'Q38A', 'Q38I', 'Q38E', 'Q39A', 'Q39I', 'Q39E', 'Q40A', 'Q40I', 'Q40E', 'Q41A', 'Q41I', 'Q41E', 'Q42A', 'Q42I', 'Q42E', 'source', 'introel

In [169]:
#If a person has taken more than 25s to answer a question, that response is not reliable and so we will not consider it
#for i in range(0,124):
#    for j in range(0, 39775):
#        if(data.iloc[j, i+2] > 25000):
#            data.iloc[j, i] = 0
#        j = j+1
#    i = i+3



In [170]:
print(data["Q1A"])

0        3
1        3
2        2
3        1
4        1
5        0
6        0
7        0
8        3
9        2
10       2
11       2
12       0
13       0
14       0
15       2
16       2
17       2
18       2
19       1
20       2
21       2
22       2
23       2
24       1
25       3
26       3
27       1
28       3
29       0
        ..
39745    3
39746    2
39747    1
39748    3
39749    3
39750    2
39751    2
39752    3
39753    2
39754    1
39755    3
39756    3
39757    3
39758    3
39759    1
39760    1
39761    1
39762    0
39763    1
39764    1
39765    3
39766    1
39767    3
39768    1
39769    2
39770    1
39771    2
39772    1
39773    2
39774    1
Name: Q1A, Length: 39775, dtype: int64


In [171]:
#creating outcome columns for Stress, Anxiety and Depression
#stress_scale = []
#def Stress_scale(stress):
#    if stress <=14:
#        stress_scale.append("Normal S")
#    elif stress >14 and stress <=18:
#        stress_scale.append("Mild S")
#    elif stress >18 and stress <= 25:
#        stress_scale.append("Moderate S")
#    elif stress > 25 and stress <= 33:
#        stress_scale.append("Severe S")
#    else:
#        stress_scale.append("Extremely S")
#    return stress_scale
      
        
stress = data["Q1A"] + data["Q6A"] + data["Q8A"] + data["Q11A"] + data["Q12A"] + data["Q14A"] + data["Q18A"] + data["Q22A"] +data["Q27A"] + data["Q29A"] + data["Q32A"] + data["Q33A"] + data["Q35A"] + data["Q39A"]
#print(stress)
data["Stress"] = stress 
data["Stress_R"] = stress #column to be used for regression approach
data["Stress"] = data["Stress"].apply(lambda stress: 'Normal S' if stress <=14 else ('Mild S' if stress >14 and stress <=18 else ('Moderate S' if stress >18 and stress <= 25 else('Severe S' if stress > 25 and stress <= 33 else 'Extremely S')))) #column used for classification approach
#data["Stress_scale"] = data["Stress"].apply(Stress_scale)
#data["Stress_scale"] = Stress_scale(data[["Stress"]])

anxiety = data["Q2A"] + data["Q4A"] + data["Q7A"] + data["Q9A"] + data["Q15A"] + data["Q19A"] + data["Q20A"] + data["Q23A"] +data["Q25A"] + data["Q28A"] + data["Q30A"] + data["Q36A"] + data["Q40A"] + data["Q41A"]
data["Anxiety"] = anxiety
data["Anxiety_R"] = anxiety
data["Anxiety"] = data["Anxiety"].apply(lambda anxiety: 'Normal A' if anxiety <=7 else ('Mild A' if anxiety >7 and anxiety <=9 else ('Moderate A' if anxiety >9 and anxiety <= 14 else('Severe A' if anxiety > 14 and anxiety <= 19 else 'Extremely A'))))


depression = data["Q3A"] + data["Q5A"] + data["Q10A"] + data["Q13A"] + data["Q16A"] + data["Q17A"] + data["Q21A"] + data["Q24A"] + data["Q26A"] + data["Q31A"] + data["Q34A"] + data["Q37A"] + data["Q38A"] + data["Q42A"] 
data["Depression"] = depression
data["Depression_R"] = depression
data["Depression"] = data["Depression"].apply(lambda depression: 'Normal D' if depression <=9 else ('Mild D' if depression >9 and depression <=13 else ('Moderate D' if depression >9 and depression <= 14 else('Severe D' if depression > 14 and depression <= 19 else 'Extremely D'))))
print(data["Anxiety"])
#anxiety = data

0        Extremely A
1           Severe A
2         Moderate A
3           Severe A
4        Extremely A
5           Normal A
6           Severe A
7           Normal A
8        Extremely A
9        Extremely A
10          Normal A
11       Extremely A
12        Moderate A
13          Severe A
14          Normal A
15          Normal A
16          Severe A
17          Normal A
18          Normal A
19            Mild A
20          Normal A
21          Normal A
22       Extremely A
23        Moderate A
24        Moderate A
25       Extremely A
26       Extremely A
27       Extremely A
28       Extremely A
29          Normal A
            ...     
39745    Extremely A
39746    Extremely A
39747       Normal A
39748       Severe A
39749    Extremely A
39750    Extremely A
39751    Extremely A
39752    Extremely A
39753     Moderate A
39754       Normal A
39755       Severe A
39756       Severe A
39757       Normal A
39758    Extremely A
39759     Moderate A
39760       Normal A
39761       N

In [172]:
import matplotlib.pyplot as plt

#plt.scatter(data['Stress_R'], data['age'])
#plt.plot(data['Depression_R'])
#plt.plot(data['Anxiety_R'])


In [173]:
teen_data = (data['age'] > 12) & (data['age'] <= 19)
teen_data = data.loc[teen_data]
teen_data

Q1A  Q1I    Q1E  Q2A  Q2I   Q2E  Q3A  Q3I    Q3E  Q4A  ...  race  \
0        3   28   3890    3   25  2122    1   16   1944    3  ...    10   
1        3    1   8118    0   36  2890    1   35   4777    2  ...    70   
2        2    7   5784    0   33  4373    3   41   3242    0  ...    60   
3        1   23   5081    2   11  6837    1   37   5521    0  ...    70   
4        1   36   3215    1   13  7731    2    5   4156    3  ...    10   
6        0   20   4325    0   34  4009    1   38   3604    2  ...    60   
8        3    3   3470    3   14  2139    2    0  11043    3  ...    70   
9        2   38   5187    1   28  2600    3    9   2015    0  ...    60   
10       2   38   3352    0   16  4322    1   28   3083    0  ...    60   
11       2   37   4024    2   35  2116    1   18   3408    1  ...    60   
15       2   17   2316    0   18  2450    1   11   3143    1  ...    60   
16       2   15   2789    0    2  4500    1   25   3900    1  ...    60   
17       2   17   2507    0   27  1334    1   38   1864    0  ...    60   
18       2    5   6729    1    3  4793    1   20   3328    0  ...    60   
19       1    8   4144    1   27  4442    1   37   7254    0  ...    50   
20       2    0   9774    0   38  2011    1   28   2618    0  ...    60   
21       2   41  50135    0   11  2033    1   38   3882    0  ...    60   
23       2   14   6074    1    6  5943    1   31   4097    1  ...    70   
25       3   23   2453    0    6  7105    3   21   1923    1  ...    10   
26       3    0   4820    3   39  1109    3    8   1833    3  ...    60   
27       1   28   2984    1   35  3838    0   11   3116    1  ...    60   
28       3   12   2431    2    2  9289    3   15   3330    3  ...    70   
29       0    9   2236    0   10  1437    1    7   2570    0  ...    70   
30       1   35   1531    1   22  2909    2   31   3694    0  ...    70   
31       1   25   3671    1   26  5743    1   13   3154    0  ...    60   
33       1   41   4705    0   42  2187    1   11   3007    0  ...    60   
34       0   27   2461    0   28  3712    1   11   3302    0  ...    60   
35       0   39   2673    2    9  3719    0   30   2771    0  ...    10   
38       1    5   2844    1   15  3449    2   34   2585    2  ...    10   
41       2   18   2547    0   11  1495    2   17   1882    0  ...    60   
...    ...  ...    ...  ...  ...   ...  ...  ...    ...  ...  ...   ...   
39646    3   27   2570    0   29  1475    2    0   3175    2  ...    60   
39654    1    5  22799    1    7  5081    2   41    653    3  ...    10   
39662    2   10   5483    3    9  5868    2   39   4204    2  ...    10   
39665    0   37   2104    1   16  3415    0   32   1863    0  ...    10   
39677    2    8   1406    0   28  1938    3    3   3281    2  ...    60   
39690    2   12   3497    0    6  5203    1    1  11790    2  ...    50   
39697    1    0   6737    0    2  2887    1   12   2568    3  ...    60   
39699    2    9  10335    3   11  6698    0   19   8544    0  ...    20   
39701    3   36   2306    3   42  2206    1   17   2638    1  ...    60   
39702    1    7   4005    0   24  2799    0   13   3889    1  ...    60   
39704    2   36   2968    0   39  3593    2   17   4116    0  ...    20   
39707    3   38   2350    1   29  2316    3   20   2087    3  ...    60   
39720    0   35   2155    1   34  3256    1   25   3381    0  ...    60   
39724    3   42   2070    3   26  2022    2   10   4210    1  ...    10   
39730    1   24   3400    2   25  3833    1    8   6406    0  ...    70   
39735    0   41   4081    1   10  7567    1   31   3196    0  ...    10   
39737    3   24   2999    2   14  1998    1   41   3219    2  ...    10   
39738    3   20  23562    3   29  4048    2   41   3720    0  ...    10   
39740    3   13   2459    3   38  2413    3   22   2649    2  ...    10   
39744    3   31   2913    3   33  2296    3   39   2706    1  ...    10   
39745    3    5   5117    3   22  2535    2   40   5404    1  ...    10   
39746    2   21   4993    1   36

In [174]:
modeldataR = teen_data[['Q1A','Q6A','Q8A','Q11A','Q12A','Q14A','Q18A','Q22A','Q27A','Q29A','Q32A','Q33A','Q35A','Q39A',
"Q2A","Q4A","Q7A","Q9A","Q15A","Q19A","Q20A","Q23A","Q25A","Q28A","Q30A","Q36A","Q40A","Q41A","Q3A","Q5A","Q10A","Q13A","Q16A","Q17A","Q21A","Q24A","Q26A","Q31A","Q34A","Q37A","Q38A","Q42A",'age','Stress_R','Depression_R','Anxiety_R']]

In [175]:
#splittin the data in train and test sets
from sklearn.model_selection import train_test_split



In [176]:
X = modeldataR.iloc[:, :43].values
Y = modeldataR.iloc[:, 43:].values

x_train, x_test, y_train, y_test = train_test_split(X, Y, 
    test_size=0.2, random_state= 8)

In [177]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(11060, 43)
(11060, 3)
(2765, 43)
(2765, 3)


First approach - Using Regression method

In [178]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.multioutput import MultiOutputClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import LinearSVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [179]:
#Implementing Linear Regression 

log_model = LinearRegression()
wrapper = MultiOutputRegressor(estimator = log_model)
# fit model
wrapper.fit(x_train, y_train)


MultiOutputRegressor(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
           n_jobs=None)

In [180]:
log_pred = wrapper.predict(x_test)

log_pred = log_pred.astype(int)
print(log_pred)

[[29 38 24]
 [15  5  7]
 [39 35 37]
 ...
 [ 4  4  5]
 [25 40 18]
 [11  8 14]]


In [181]:
log_accuracy = np.mean(log_pred == y_test)

print(log_accuracy)

0.5112718505123568


In [182]:
#Implementing Random Forest
forest = RandomForestRegressor(random_state = 1)
wrapper = MultiOutputRegressor(estimator = forest)
# fit model
wrapper.fit(x_train, y_train)


/home/akshay/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/akshay/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/akshay/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


MultiOutputRegressor(estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=1, verbose=0, warm_start=False),
           n_jobs=None)

In [183]:
pred = wrapper.predict(x_test)

rf_pred = pred.astype(int)
print(rf_pred)

[[30 38 26]
 [15  7 10]
 [39 35 36]
 ...
 [ 6  6  5]
 [25 39 19]
 [11 10 18]]


In [184]:
accuracy = np.mean(rf_pred == y_test)

print(accuracy)

0.281374321880651


In [185]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree

In [186]:
clf = tree.DecisionTreeRegressor()
decisiontree = MultiOutputRegressor(estimator = clf)
decisiontree.fit(x_train, y_train)

MultiOutputRegressor(estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
           n_jobs=None)

In [187]:
dtpred = decisiontree.predict(x_test)
dtpred = dtpred.astype(int)
print(dtpred)

[[27 35 25]
 [19  7 14]
 [40 35 39]
 ...
 [ 5  4  4]
 [19 40 20]
 [14  7 17]]


In [188]:
dtaccu = np.mean(dtpred == y_test)

print(dtaccu)

0.20506329113924052


In [189]:
#Implementing Support Vector Machine Models

from sklearn.svm import SVC  
from sklearn.multioutput import MultiOutputClassifier

In [190]:
clfsvc = SVC(kernel='linear') 
modelsvc = MultiOutputRegressor(estimator = clfsvc)  
# fitting x samples and y classes 
modelsvc.fit(x_train, y_train)

MultiOutputRegressor(estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
           n_jobs=None)

In [191]:
predSVC = modelsvc.predict(x_test)

In [192]:
accuracySVC = np.mean(predSVC == y_test)

print(accuracySVC)

0.9997588908981314


In [193]:
#plt.scatter(x_test[:,-1], y_test[:,-1])

Using 2nd approach - Classification

In [194]:
modeldata = teen_data[['Q1A','Q6A','Q8A','Q11A','Q12A','Q14A','Q18A','Q22A','Q27A','Q29A','Q32A','Q33A','Q35A','Q39A',
"Q2A","Q4A","Q7A","Q9A","Q15A","Q19A","Q20A","Q23A","Q25A","Q28A","Q30A","Q36A","Q40A","Q41A",'age',"Q3A","Q5A","Q10A","Q13A","Q16A","Q17A","Q21A","Q24A","Q26A","Q31A","Q34A","Q37A","Q38A","Q42A",'Stress','Depression','Anxiety']]


len(modeldata.columns)

46

In [195]:
X = modeldata.iloc[:, :43].values
Y = modeldata.iloc[:, 43:].values

x_train, x_test, y_train, y_test = train_test_split(X, Y, 
    test_size=0.2, random_state= 8)

In [196]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(11060, 43)
(11060, 3)
(2765, 43)
(2765, 3)


In [197]:
X_trainA = x_train[:, 14:29]
Y_trainA = y_train[:, -1]

X_testA = x_test[:, 14:29]
Y_testA = y_test[:, -1]

print(X_trainA.shape)
print(Y_trainA.shape)
print(X_testA.shape)
print(Y_testA.shape)

(11060, 15)
(11060,)
(2765, 15)
(2765,)


In [198]:
#Implementing Logistic Regression for Anxiety 

from sklearn.linear_model import LogisticRegression

modelA = LogisticRegression(random_state=0, multi_class='multinomial', solver='saga',max_iter=10000).fit(X_trainA, Y_trainA)


In [199]:
lrpredA = modelA.predict(X_testA)

In [200]:
modelA.score(X_trainA, Y_trainA)

1.0

In [201]:
lraccuracyA = np.mean(lrpredA == Y_testA)

print(lraccuracyA)

0.9996383363471971


In [202]:
from sklearn.metrics import classification_report

print(classification_report(Y_testA, lrpredA))

              precision    recall  f1-score   support

 Extremely A       1.00      1.00      1.00      1297
      Mild A       1.00      0.99      1.00       172
  Moderate A       1.00      1.00      1.00       426
    Normal A       1.00      1.00      1.00       423
    Severe A       1.00      1.00      1.00       447

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [203]:
#Implementing Random Forest for Anxiety
# Import the model we are using
from sklearn.ensemble import RandomForestClassifier


In [204]:
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf = rf.fit(X_trainA, Y_trainA)

In [205]:
# Use the forest's predict method on the test data
rfpredA = rf.predict(X_testA)

rfaccuracyA = np.mean(rfpredA == Y_testA)

print(rfaccuracyA)

0.8806509945750453


In [206]:
from sklearn import metrics

print("Accuracy score is", metrics.accuracy_score(Y_testA, rfpredA ))

Accuracy score is 0.8806509945750453


In [207]:
print(classification_report(Y_testA, rfpredA))

              precision    recall  f1-score   support

 Extremely A       0.96      0.97      0.97      1297
      Mild A       0.69      0.20      0.31       172
  Moderate A       0.74      0.88      0.80       426
    Normal A       0.85      0.98      0.91       423
    Severe A       0.84      0.78      0.81       447

   micro avg       0.88      0.88      0.88      2765
   macro avg       0.82      0.76      0.76      2765
weighted avg       0.88      0.88      0.87      2765



In [208]:
#Implementing Decision Tree for Anxiety

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [209]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_trainA, Y_trainA)

In [210]:
dtpredA = dt.predict(X_testA)

dtaccuracyA = np.mean(dtpredA == Y_testA)

print(dtaccuracyA)

0.7529837251356238


In [211]:
print(classification_report(Y_testA, dtpredA))

              precision    recall  f1-score   support

 Extremely A       0.92      0.92      0.92      1297
      Mild A       0.37      0.35      0.36       172
  Moderate A       0.55      0.57      0.56       426
    Normal A       0.82      0.86      0.84       423
    Severe A       0.54      0.51      0.52       447

   micro avg       0.75      0.75      0.75      2765
   macro avg       0.64      0.64      0.64      2765
weighted avg       0.75      0.75      0.75      2765



In [212]:
#Implementing Support Vector Machine for Anxiety
from sklearn.svm import SVC 

In [213]:
svm = SVC(kernel = 'linear')
svm = svm.fit(X_trainA, Y_trainA)

In [214]:
svmpredA = svm.predict(X_testA)

svmaccuracyA = np.mean(svmpredA == Y_testA)

print(svmaccuracyA)

1.0


In [215]:
print(classification_report(Y_testA, svmpredA))

              precision    recall  f1-score   support

 Extremely A       1.00      1.00      1.00      1297
      Mild A       1.00      1.00      1.00       172
  Moderate A       1.00      1.00      1.00       426
    Normal A       1.00      1.00      1.00       423
    Severe A       1.00      1.00      1.00       447

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [216]:
#Implementing Naive Bayes for Anxiety
from sklearn.naive_bayes import GaussianNB

In [217]:
gnb = GaussianNB()
gnb = gnb.fit(X_trainA, Y_trainA)

In [218]:
gnbpredA = gnb.predict(X_testA)

gnbaccuracyA = np.mean(gnbpredA == Y_testA)

print(gnbaccuracyA)

0.8209764918625678


In [219]:
print(classification_report(Y_testA, gnbpredA))

              precision    recall  f1-score   support

 Extremely A       1.00      0.86      0.93      1297
      Mild A       0.52      0.34      0.41       172
  Moderate A       0.69      0.83      0.75       426
    Normal A       0.91      0.86      0.88       423
    Severe A       0.61      0.85      0.71       447

   micro avg       0.82      0.82      0.82      2765
   macro avg       0.74      0.75      0.74      2765
weighted avg       0.84      0.82      0.82      2765



In [220]:
X_trainA.shape

(11060, 15)

Model training for Stress

In [221]:
modeldataS = teen_data[['age','Q1A','Q6A','Q8A','Q11A','Q12A','Q14A','Q18A','Q22A','Q27A','Q29A','Q32A','Q33A','Q35A','Q39A',
"Q2A","Q4A","Q7A","Q9A","Q15A","Q19A","Q20A","Q23A","Q25A","Q28A","Q30A","Q36A","Q40A","Q41A","Q3A","Q5A","Q10A","Q13A","Q16A","Q17A","Q21A","Q24A","Q26A","Q31A","Q34A","Q37A","Q38A","Q42A",'Stress','Depression','Anxiety']]


In [222]:
X = modeldataS.iloc[:, :43].values
Y = modeldataS.iloc[:, 43:].values

x_train, x_test, y_train, y_test = train_test_split(X, Y, 
    test_size=0.2, random_state= 8)

In [223]:
X_trainS = x_train[:, :15]
Y_trainS = y_train[:, -3]

X_testS = x_test[:, :15]
Y_testS = y_test[:, -3]

print(X_trainS.shape)
print(Y_trainS.shape)
print(X_testS.shape)
print(Y_testS.shape)

(11060, 15)
(11060,)
(2765, 15)
(2765,)


In [224]:
#Implementing Logistic Regression for Stress

modelS = LogisticRegression(random_state=0, multi_class='multinomial', solver='saga',max_iter=10000).fit(X_trainS, Y_trainS)


In [225]:
lrpredS = modelS.predict(X_testS)

In [226]:
modelS.score(X_trainS, Y_trainS)

1.0

In [227]:
lraccuracyS = np.mean(lrpredS == Y_testS)

print(lraccuracyS)

0.9996383363471971


In [228]:
print(classification_report(Y_testS, lrpredS))

              precision    recall  f1-score   support

 Extremely S       1.00      1.00      1.00       508
      Mild S       1.00      1.00      1.00       326
  Moderate S       1.00      1.00      1.00       649
    Normal S       1.00      1.00      1.00       597
    Severe S       1.00      1.00      1.00       685

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [229]:
#Implementing Random Forest for Stress


In [230]:
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf = rf.fit(X_trainS, Y_trainS)

In [231]:
# Use the forest's predict method on the test data
rfpredS = rf.predict(X_testS)

rfaccuracyS = np.mean(rfpredS == Y_testS)

print(rfaccuracyS)

0.9009041591320073


In [232]:

print("Accuracy score is", metrics.accuracy_score(Y_testS, rfpredS ))

Accuracy score is 0.9009041591320073


In [233]:
print(classification_report(Y_testS, rfpredS))

              precision    recall  f1-score   support

 Extremely S       0.97      0.92      0.95       508
      Mild S       0.86      0.65      0.74       326
  Moderate S       0.85      0.92      0.88       649
    Normal S       0.93      0.97      0.95       597
    Severe S       0.89      0.93      0.91       685

   micro avg       0.90      0.90      0.90      2765
   macro avg       0.90      0.88      0.89      2765
weighted avg       0.90      0.90      0.90      2765



In [234]:
#Implementing Decision Tree for Stress

In [235]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_trainS, Y_trainS)

In [236]:
dtpredS = dt.predict(X_testS)

dtaccuracyS = np.mean(dtpredS == Y_testS)

print(dtaccuracyS)

0.7403254972875226


In [237]:
print(classification_report(Y_testS, dtpredS))

              precision    recall  f1-score   support

 Extremely S       0.85      0.85      0.85       508
      Mild S       0.48      0.49      0.49       326
  Moderate S       0.70      0.66      0.68       649
    Normal S       0.85      0.87      0.86       597
    Severe S       0.73      0.74      0.73       685

   micro avg       0.74      0.74      0.74      2765
   macro avg       0.72      0.72      0.72      2765
weighted avg       0.74      0.74      0.74      2765



In [238]:
#Implementing SVM for Stress


In [239]:
svm = SVC(kernel = 'linear')
svm = svm.fit(X_trainS, Y_trainS)

In [240]:
svmpredS = svm.predict(X_testS)

svmaccuracyS = np.mean(svmpredS == Y_testS)

print(svmaccuracyS)

1.0


In [241]:
print(classification_report(Y_testS, svmpredS))

              precision    recall  f1-score   support

 Extremely S       1.00      1.00      1.00       508
      Mild S       1.00      1.00      1.00       326
  Moderate S       1.00      1.00      1.00       649
    Normal S       1.00      1.00      1.00       597
    Severe S       1.00      1.00      1.00       685

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [242]:
#Implementing Naive Bayes for Stress

In [243]:
gnb = GaussianNB()
gnb = gnb.fit(X_trainS, Y_trainS)

In [244]:
gnbpredS = gnb.predict(X_testS)

gnbaccuracyS = np.mean(gnbpredS == Y_testS)

print(gnbaccuracyS)

0.894755877034358


In [245]:
X_trainS.shape

(11060, 15)

In [246]:
print(classification_report(Y_testS, gnbpredS))

              precision    recall  f1-score   support

 Extremely S       0.96      0.86      0.91       508
      Mild S       0.75      0.85      0.80       326
  Moderate S       0.87      0.94      0.90       649
    Normal S       1.00      0.88      0.93       597
    Severe S       0.87      0.92      0.89       685

   micro avg       0.89      0.89      0.89      2765
   macro avg       0.89      0.89      0.89      2765
weighted avg       0.90      0.89      0.90      2765



# Model for Depression

In [247]:
modeldataD = teen_data[['Q1A','Q6A','Q8A','Q11A','Q12A','Q14A','Q18A','Q22A','Q27A','Q29A','Q32A','Q33A','Q35A','Q39A',
"Q2A","Q4A","Q7A","Q9A","Q15A","Q19A","Q20A","Q23A","Q25A","Q28A","Q30A","Q36A","Q40A","Q41A","Q3A","Q5A","Q10A","Q13A","Q16A","Q17A","Q21A","Q24A","Q26A","Q31A","Q34A","Q37A","Q38A","Q42A",'age','Stress','Depression','Anxiety']]


In [248]:
X = modeldataD.iloc[:, :43].values
Y = modeldataD.iloc[:, 43:].values

x_train, x_test, y_train, y_test = train_test_split(X, Y, 
    test_size=0.2, random_state= 8)

In [249]:
X_trainD = x_train[:, 28:43]
Y_trainD = y_train[:, -2]

X_testD = x_test[:, 28:43]
Y_testD = y_test[:, -2]

print(X_trainD.shape)
print(Y_trainD.shape)
print(X_testD.shape)
print(Y_testD.shape)

(11060, 15)
(11060,)
(2765, 15)
(2765,)


In [250]:
#Implementing Logistic Regression for Depression

modelD = LogisticRegression(random_state=0, multi_class='multinomial', solver='saga',max_iter=10000).fit(X_trainD, Y_trainD)


In [251]:
lrpredD = modelD.predict(X_testD)

In [252]:
modelD.score(X_trainD, Y_trainD)

0.9954792043399638

In [253]:
lraccuracyD = np.mean(lrpredD == Y_testD)

print(lraccuracyD)

0.9927667269439421


In [254]:
print(classification_report(Y_testD, lrpredD))

              precision    recall  f1-score   support

 Extremely D       1.00      1.00      1.00      1680
      Mild D       0.97      1.00      0.98       232
  Moderate D       1.00      0.68      0.81        63
    Normal D       1.00      1.00      1.00       461
    Severe D       0.96      1.00      0.98       329

   micro avg       0.99      0.99      0.99      2765
   macro avg       0.99      0.94      0.96      2765
weighted avg       0.99      0.99      0.99      2765



In [255]:
#Implementing Random Forest for Depression

In [256]:
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf = rf.fit(X_trainD, Y_trainD)

In [257]:
# Use the forest's predict method on the test data
rfpredD = rf.predict(X_testD)

rfaccuracyD = np.mean(rfpredD == Y_testD)

print(rfaccuracyD)

0.9316455696202531


In [258]:
print("Accuracy score is", metrics.accuracy_score(Y_testD, rfpredD ))

Accuracy score is 0.9316455696202531


In [259]:
print(classification_report(Y_testD, rfpredD))

              precision    recall  f1-score   support

 Extremely D       0.98      0.99      0.98      1680
      Mild D       0.80      0.76      0.78       232
  Moderate D       0.56      0.08      0.14        63
    Normal D       0.93      0.98      0.95       461
    Severe D       0.81      0.84      0.82       329

   micro avg       0.93      0.93      0.93      2765
   macro avg       0.81      0.73      0.74      2765
weighted avg       0.92      0.93      0.92      2765



In [260]:
#Implementing Decision Tree for Depression

In [261]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_trainD, Y_trainD)

In [262]:
dtpredD = dt.predict(X_testD)

dtaccuracyD = np.mean(dtpredD == Y_testD)

print(dtaccuracyD)

0.850632911392405


In [263]:
print(classification_report(Y_testD, dtpredD))

              precision    recall  f1-score   support

 Extremely D       0.95      0.96      0.96      1680
      Mild D       0.54      0.53      0.53       232
  Moderate D       0.20      0.19      0.20        63
    Normal D       0.88      0.88      0.88       461
    Severe D       0.61      0.62      0.62       329

   micro avg       0.85      0.85      0.85      2765
   macro avg       0.64      0.64      0.64      2765
weighted avg       0.85      0.85      0.85      2765



In [264]:
#Implementing the SVM model for Depression

In [265]:
svm = SVC(kernel = 'linear')
svm = svm.fit(X_trainD, Y_trainD)

In [266]:
svmpredD = svm.predict(X_testD)

svmaccuracyD = np.mean(svmpredD == Y_testD)

print(svmaccuracyD)

1.0


In [267]:
print(classification_report(Y_testD, svmpredD))

              precision    recall  f1-score   support

 Extremely D       1.00      1.00      1.00      1680
      Mild D       1.00      1.00      1.00       232
  Moderate D       1.00      1.00      1.00        63
    Normal D       1.00      1.00      1.00       461
    Severe D       1.00      1.00      1.00       329

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [268]:
print(classification_report(Y_testD, svmpredD))

              precision    recall  f1-score   support

 Extremely D       1.00      1.00      1.00      1680
      Mild D       1.00      1.00      1.00       232
  Moderate D       1.00      1.00      1.00        63
    Normal D       1.00      1.00      1.00       461
    Severe D       1.00      1.00      1.00       329

   micro avg       1.00      1.00      1.00      2765
   macro avg       1.00      1.00      1.00      2765
weighted avg       1.00      1.00      1.00      2765



In [269]:
#Implementing Naive Bayes for Depression

In [270]:
gnb = GaussianNB()
gnb = gnb.fit(X_trainD, Y_trainD)

In [271]:
gnbpredD = gnb.predict(X_testD)

gnbaccuracyD = np.mean(gnbpredD == Y_testD)

print(gnbaccuracyD)

0.854249547920434


In [272]:
print(classification_report(Y_testD, gnbpredD))

              precision    recall  f1-score   support

 Extremely D       1.00      0.86      0.92      1680
      Mild D       0.67      0.87      0.76       232
  Moderate D       0.00      0.00      0.00        63
    Normal D       1.00      0.87      0.93       461
    Severe D       0.52      0.98      0.68       329

   micro avg       0.85      0.85      0.85      2765
   macro avg       0.64      0.71      0.66      2765
weighted avg       0.89      0.85      0.86      2765

